### ISSUE TITLE
Does the Dockerfile specify the installation of system level packages needed for dsGeo?

### ISSUE THREAD

**Issue by tombisho** [obiba/docker-rock-demo#1]
I am wondering if the system level dependencies are installed for dsGeo. It would be helpful to see how this is done, presumably [here](https://github.com/tombisho/docker-rock-surv/blob/main/Dockerfile#L18)

we would specify something like:

`apt-get install gdal-bin proj-bin libgdal-dev libproj-dev`

It would be useful to know this for beginners like me

**Comment by ymarcon** [comment]
It's because it is already in the `obiba/rock` image (the layer before the `datashield/rock-base` one):
https://github.com/obiba/docker-rock/blob/main/Dockerfile#L57
but you are right, it should be moved to the image where the dsGeo package is.
